name: Build and deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout Kamelet Catalogue
        uses: actions/checkout@v2
        with:
          repository: apache/camel-kamelets
          path: camel-kamelets

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Kamelet Catalogue
        run: mvn install -f camel-kamelets

      - name: Test application
        run: ./mvnw compile test -f main

      - name: Build application
        run: |
          ./mvnw package -f main -DskipTest \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.username=${{ secrets.DOCKERHUB_USERNAME }} \
          -Dquarkus.container-image.password=${{ secrets.DOCKERHUB_TOKEN }}
